#!/usr/bin/bash

# Brightness notification: dunst

icon_path=/usr/share/pixmaps/sun.png

# you can also use : xbacklight 
# sudo pacman -S xbacklight - and then xbacklight -G should output the current brightness
# this implementation is using xbacklight

# xbacklight comes by default in XFCE 

function get_brightness {
    light -G
}

function brightness_notification {
    brightness=`get_brightness`
    printf -v br_int %.0f "$brightness"
    echo $br_int
    bar=$(seq -s "─" $(($br_int / 5)) | sed 's/[0-9]//g')
    dunstify -r 817 -u normal -i ${icon_path} "Current Brightness: "${br_int}"%" $bar
}

case $1 in
    up)
        light -A 5
        brightness_notification
        ;;
    down)
        light -U 5
        brightness_notification
	    ;;
    *)
        echo "Usage: $0 up | down "
        ;;
esac
